credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: <hashed_password>  # Use the hashed password (explained below)
      group: admin
    supervisor:
      email: supervisor@example.com
      name: Supervisor User
      password: <hashed_password>
      group: supervisor
    user:
      email: user@example.com
      name: Regular User
      password: <hashed_password>
      group: user
cookie:
  expiry_days: 365
  key: some_signature_key
  name: some_cookie_name