users:
  admin:
    created: true
    department: DHASE
    name: AHODEKON MAXIES
    password: $2b$12$XPUgNhch8nyNkr5jTGR9ruvZ6KtP6M73c43UhM4fbrzCdtZ3lOjku
    roles:
    - users
    - budget
    - "requete"
    - "reconciliation"
    - dashboard
    username: nmaxies
